#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM echo-lambda

# Copy the Runtime API Daemon and name it aws-lambda-rie, as the ENTRYPOINT is
# set to use /usr/local/bin/aws-lambda-rie to be compatible with AWS images.
COPY lambda-runtime-api-daemon /usr/local/bin/aws-lambda-rie

#-------------------------------------------------------------------------------
# Build Lambda and push to local registry hosted on local k8s
# cp ${PWD}/../../../bin/lambda-runtime-api-daemon .
# docker build -t localhost:5000/echo-lambda-rapid -f Dockerfile-echo .
# docker push localhost:5000/echo-lambda-rapid
# rm lambda-runtime-api-daemon

# Check containers are present in local registry
# curl http://localhost:5000/v2/_catalog

# Deploy to OpenFaaS
# faas-cli deploy -f ./openfaas-function-stack.yaml

# OpenFaaS
# curl -XPOST "http://localhost:8080/function/echo-lambda" -d '{"key": "value"}'
