#!/bin/bash

# the path to the interpreter and all of the originally intended arguments
args=("$@")

# the extra options we want to pass to the interpreter
extra_args=("-X" "importtime")

# insert the extra options. Note that the original version of this script
# https://github.com/aws-samples/aws-lambda-extensions/blob/main/bash-example-wrapper/wrapper_script
# https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper
# has the args inserted as follows:
#args=("${args[@]:0:$#-1}" "${extra_args[@]}" "${args[@]: -1}")
# That approach inserts -X importtime immediately before the last arg. That
# works for the AWS base images, which launch the runtime like:
# /var/lang/bin/python3.8 /var/runtime/bootstrap.py
# but for custom images using awslambdaric that won't work as those launch with
# python3 -m awslambdaric "$1"
# Instead we insert -X importtime immeduately after the first arg as that
# will work for both AWS base images and custom images.
args=("${args[@]:0:1}" "${extra_args[@]}" "${args[@]:1}")

# start the runtime with the extra options
exec "${args[@]}"   
