#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM golang:1.22 AS builder
WORKDIR /go/src/lambda-runtime-api-daemon
COPY . .
RUN cd examples/echo/echo-clients && make dep && make rpcclient

FROM scratch
COPY --from=builder /go/src/lambda-runtime-api-daemon/examples/echo/echo-clients/rpcclient /usr/bin/rpcclient
ENTRYPOINT ["/usr/bin/rpcclient"]

#-------------------------------------------------------------------------------
#
# Build the image. Note using .. not . here to reference the Docker context
# in the parent directory.
# docker build -t rpcclient -f ./Dockerfile-rpcclient ..
#
